"""init

Revision ID: d38051e1a30a
Revises: 
Create Date: 2026-09-25 00:34:59.072104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38051e1a30a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_filters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('min_budget', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_listings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=10), nullable=True),
    sa.Column('status_id', sa.BigInteger(), nullable=True),
    sa.Column('status_name', sa.String(length=100), nullable=True),
    sa.Column('employer_id', sa.BigInteger(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('job_listing_skills',
    sa.Column('job_listing_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('job_listing_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_listing_skills')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('job_listings')
    op.drop_table('job_filters')
    # ### end Alembic commands ###
